---
- name: deployment of RabbitMQ for the SON-SP VM appliance as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Docker Registry

  - name: Log into private registry and force re-authorization
    docker_login:
      registry_url: registry.sonata-nfv.eu:5000
      username: "{{ registry_user }}"
      password: "{{ registry_pass }}"
      reauthorize: yes

# Running the Sonata BROKER Docker Image

  - name: run the "SP Message Bus"
    docker_container: 
      name: broker
      image: registry.sonata-nfv.eu:5000/broker
      state: started
      ports: 5672
