---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - pull images to the local repository
    docker_image: 
      name: son-pluginmanager
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest

  - name: MANO Service Life-cycle Management - pull images to the local repository
    docker_image:
      name: son-servicelifecyclemanagement
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest

  - name: MANO Infrastructure Abstractor - pull images to the local repository
    docker_image:
      name: son-sp-infrabstract
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: son-pluginmanager
      image: son-pluginmanager
      state: started
      ports: 8001

  - name: MANO Service Life-cycle Management - running Docker containers
    docker_container:
      name: son-servicelifecyclemanagement
      image: son-servicelifecyclemanagement
      state: started
      # ports:

  - name: MANO Infrastructure Abstractor - running Docker containers
    docker_container:
      name: son-sp-infrabstract
      image: son-sp-infrabstract
      state: started
      # ports:
