---
- name: deploy Docker containers from private Registry to the SP VM
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Registry

- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.sonata-nfv.eu
    username: sonata
    password: $0n@t@
    reauthorize: yes

# Getting the Sonata Docker Images

  - name: pull Monitory images to local repository\
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu
      state: started
      tag: latest
      with items:
      - son-monitor-influxdb
      - son-monitor-mysql
      - son-monitor-pusggateway
      - son-monitor-prometheus
      - son-monitor-manager
      - son-monitor-probe
