---
- name: deployment of SP GATEKEEPER as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Registry

- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.sonata-nfv.eu
    username: sonata
    password: $0n@t@
    reauthorize: yes

# Getting the Sonata Docker Images

  - name: pull GK modules images to local repository
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu
      state: started
      tag: latest
      with items:
      - son-gk-gui
      - son-gk-bss
      - son-gtkpkg
      - son-gtksrv
      - son-gtkapi
