---
- name: deployment of RabbitMQ for the SON-SP VM appliance as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Docker Registry

#  - name: Log into private registry and force re-authorization
#    docker_login:
#      registry_url: registry.sonata-nfv.eu:5000
#      username: sonata-nfv
#      password: s0n@t@
#      reauthorize: yes

# Running the Sonata BROKER Docker Image

  - name: run the "SP Message Bus"
    docker_container: 
      name: broker
      image: rabbitmq
      env:
        RABBITMQ_CONSOLE_LOG: new
      state: started
      ports: "5672:5672, 8080:15672"
      privileged: yes
