---
- name: deploy Docker containers from private Registry to the SP VM
  hosts: "{{ targets }}"
  vars:
    upassword: 123qwe
    dbname: son-sp
    dbuser: root
  sudo: yes
  tasks:

# Running the Sonata MONITORY Docker Images

  - name: MONIT InfluxDB  - running Docker containers
    docker_container:
      name: son-monitor-influxdb
      image: sonatanfv/son-monitor-influxdb
      state: started
      ports: 8086:8086


  - name: MONIT MySQL - running Docker containers
    docker_container:
      name: son-monitor-mysql
      image: sonatanfv/son-monitor-mysql
      env:
        MYSQL_ROOT_PASSWORD: "{{ upassword }}"
        #MYSQL_USER: "{{ dbuser }}"
        #MYSQL_PASSWORD: "{{ upassword }}"
        MYSQL_DATABASE: "{{ dbname }}"
      state: started
      ports: 3306

  - name: MONIT Push Gateway - running Docker containers
    docker_container:
      name: son-monitor-pushgateway
      image: sonatanfv/son-monitor-pushgateway
      state: started
      ports: 9091

  - name: MONIT - running Docker containers
    docker_container:
      name: son-monitor-prometheus
      image: sonatanfv/son-monitor-prometheus
      state: started
      ports: 
      - 9090:9090
      - 9089:9089

  - name: MONIT Manager - running Docker containers
    docker_container:
      name: son-monitor-manager
      image: sonatanfv/son-monitor-manager
      state: started
      ports: 8000:8000

# - name: MONIT Probe - running Docker containers
#    docker_container:
#      name: son-monitor-probe
#      image: son-monitor-probe
#      state: started
#      ports: 

