---
- name: deployment of SP GATEKEEPER as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata GK Docker Images

  - name: GATEKEEPER - pull images to local repository
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest
      with items:
      - son-gk-gui
      - son-gk-bss
      - son-gtkpkg
      - son-gtksrv
      - son-gtkapi

# Running the Sonata GK Docker Images
  - name: GATEKEEPER - running Docker containers
    docker_container: 
      name: {{ items }}
      image: son-images/{{ items }}
      state: started
      # ports: 
      with items:
      - son-gk-gui
      - son-gk-bss
      - son-gtkpkg
      - son-gtksrv
      - son-gtkapi
 
