---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata MANO Docker Images

  - name: MANO - pull images to the local repository
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest
      with items:
      - son-pluginmanager
      - son-servicelifecyclemanagement
      - son-sp-infrabstract

# Running the Sonata MANO Docker Images

  - name: MANO - running Docker containers
    docker_container:
      name: {{ items }}
      image: son-images/{{ items }}
      state: started
      # ports:
      with items:
      - son-pluginmanager
      - son-servicelifecyclemanagement
      - son-sp-infrabstract

