---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: pluginmanager
      image: registry.sonata-nfv.eu:5000/pluginmanager
      state: started
      ports: 8001

  - name: MANO Service Life-cycle Management (SLM) - running Docker containers
    docker_container:
      name: servicelifecyclemanagement
      image: registry.sonata-nfv.eu:5000/servicelifecyclemanagement
      state: started
      # ports:

  - name: MANO Function Life-cycle Management (FML) - running Docker containers
    docker_container:
      name: functionlifecyclemanagement
      image: registry.sonata-nfv.eu:5000/functionlifecyclemanagement
      state: started
      # ports:

  - name: MANO Infrastructure Abstractor - running Docker containers
    docker_container:
      name: son-sp-infrabstract
      image: registry.sonata-nfv.eu:5000/son-sp-infrabstract
      state: started
      # ports:
