---
- name: deploy Docker containers from private Registry to the SP VM
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Registry

- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.sonata-nfv.eu
    username: sonata
    password: $0n@t@
    reauthorize: yes

# Getting the Sonata Docker Images

  - name: pull RabbitMQ image tolocal repository\
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu
      state: started
      tag: latest
      with items:
      - son-broker
      - son-gui
      - son-bss
      - son-gtkpkg
      - son-gtksrv
      - son-gtkapi
      - son-catalogue-repos
      - son-pluginmanager
      - son-servicelifecyclemanagement
      - son-sp-infrabstract
      - son-monitor-influxdb
      - son-monitor-mysql
      - son-monitor-pusggateway
      - son-monitor-prometheus
      - son-monitor-manager
      - son-monitor-probe

# RabbitMQ

      
# SON-GUI


# SON-BSS


# SON-GK-PKG


# SON-GK-SRV


# SON-GK-API


# SON-CATALOG


# SON-MANO-PluginMgr


# SON-SVC-LC-MGMT


# SON-IFT-Abstraction


# SON-MONIT-InfluxDB


# SON-MONIT-MySQL


# SON-MONIT-PushGW


# SON-MONIT-Prometheus


# SON-MONIT-Mgr

