---
- name: deployment of SP GATEKEEPER as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Docker Registry

  - name: Log into private registry and force re-authorization
    docker_login:
      registry_url: registry.sonata-nfv.eu:5000
      username: "{{ registry_user }}"
      password: "{{ registry_pass }}"
      reauthorize: yes

# Running the Sonata GK Docker Images

  - name: GATEKEEPER SERVER - running Docker containers
    docker_container: 
      name: son-gtksrv
      image: registry.sonata-nfv.eu:5000/son-gtksrv
      state: started
      ports: 5300
 
  - name: GATEKEEPER PACKAGES - running Docker containers
    docker_container:
      name: son-gtkpkg
      image: registry.sonata-nfv.eu:5000/son-gtkpkg
      state: started
      ports: 5100

  - name: GATEKEEPER API - running Docker containers
    docker_container:
      name: son-gtkapi
      image: registry.sonata-nfv.eu:5000/son-gtkapi
      state: started
      ports: 32001

  - name: GATEKEEPER BSS - running Docker containers
    docker_container:
      name: son-bss
      image: registry.sonata-nfv.eu:5000/son-yo-gen-bss
      state: started
      ports: 
      - 25001
      - 25002

  - name: GATEKEEPER GUI - running Docker containers
    docker_container:
      name: son-gui
      image: registry.sonata-nfv.eu:5000/son-gui
      state: started
      ports: 80

