---
- name: deploy Docker containers REPOSITORIES from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata REPOSITORIES Docker Images

  - name: REPOs - pull image to local repository
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu
      state: started
      tag: latest
      with items:
      - son-catalogue-repos

# Running the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker_container:
      name: {{ items }}
      image: son-images/{{ items }}
      state: started
      # ports:
      with items:
      - son-catalogue-repos
