---
- name: deploy Docker containers from private Registry to the SP VM
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata MONITORY Docker Images

  - name: MONIT - pull images to local repository
    docker_image: 
      name: son-images/{{ items }}
      repository: registry.sonata-nfv.eu:5000
      state: started
      tag: latest
      with items:
      - son-monitor-influxdb
      - son-monitor-mysql
      - son-monitor-pusggateway
      - son-monitor-prometheus
      - son-monitor-manager
      - son-monitor-probe

# Running the Sonata MONITORY Docker Images
  - name: MONIT - running Docker containers
    docker_container:
      name: {{ items }}
      image: son-images/{{ items }}
      state: started
      # ports:
      with items:
      - son-monitor-influxdb
      - son-monitor-mysql
      - son-monitor-pusggateway
      - son-monitor-prometheus
      - son-monitor-manager
      - son-monitor-probe

