---
- name: deploy Docker containers REPOSITORIES from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Getting the Sonata REPOSITORIES Docker Images

  - name: REPOs - pull image to local repository
    docker_image: 
      name: son-catalogue-repos
      repository: registry.sonata-nfv.eu
      state: present
      tag: latest

# Running the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker_container:
      name: son-catalogue-repos
      image: son-catalogue-repos
      state: started
      ports: 4002
