---
- name: remove the Sonata Message Bus (based on RabbitMQ) from the SON-SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

  # Verify if the Container is running


  # Remove the Sonata BROKER Container (if running)
  - name: stop the "SP Message Bus"
    docker_container: 
      name: broker
      state: stopped
      stop_timeout: 10

  # Remove the Sonata BROKER Container (if running)
  - name: destroy the "SP Message Bus"
    docker_container:
      name: broker
      state: absent

