---
- name: remove Docker containers REPOSITORIES from the SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

# Removing the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker:
      name: son-catalogue-repos
      state: absent

