---
- name: remove PostgreSQL container from the 'target' machine
  hosts: "{{ target }}"
  sudo: yes
  tasks:
  - name: deploy postgres container
    docker_container:
      name: son-postgres
      state: absent

