---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

# Stopping the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - stopping Docker containers
    docker_container:
      name: pluginmanager
      state: stopped

#  - pause: seconds=15

  - name: MANO Service Life-cycle Management (SLM) - stopping Docker containers
    docker_container:
      name: servicelifecyclemanagement
      state: stopped

#  - name: MANO Function Life-cycle Management (FML) - stopping Docker containers
#    docker_container:
#      name: functionlifecyclemanagement
#      state: stopped

  - name: MANO Infrastructure Abstractor - stopping Docker containers
    docker_container:
      name: son-sp-infrabstract
      state: stopped
