---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: pluginmanager
      state: started

#  - pause: seconds=15

  - name: MANO Service Life-cycle Management (SLM) - running Docker containers
    docker_container:
      name: servicelifecyclemanagement
      state: started

#  - name: MANO Function Life-cycle Management (FML) - running Docker containers
#    docker_container:
#      name: functionlifecyclemanagement
#      state: started

  - name: MANO Infrastructure Abstractor - running Docker containers
    docker_container:
      name: son-sp-infrabstract
      state: started
