---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: "{{ target }}"
  #sudo: yes
  tasks:

  # Running the Sonata GK SERVICES Docker Image
  - name: GATEKEEPER SERVICES - running Docker containers
    docker_container:
      name: son-gtksrv
      image: sonatanfv/son-gtksrv
      env:
        CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ public_ip }}:5672
        DATABASE_HOST: "{{ public_ip }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
      links:
        - son-broker
      state: started
      ports: "5300:5300"
      command: sh -c -e "bundle install; bundle exec rake db:migrate"
      #detach: false
