---
- name: deploy Docker containers from Registry to the SP VM
  hosts: "{{ target }}"
  vars:
    upassword: sonata
    urootpw: 1234
    dbname: monitoring
    dbuser: monitoringuser
  sudo: yes
  roles:
  - monit
