---
- name: stop REPOSITORIES Docker containers at SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

# Stopping the Sonata REPOs Docker Images

  - name: REPOs - stopping Docker containers
    docker:
      name: son-catalogue-repos
      state: stopped

