---
- name: UNINSTALLING MongDB database server
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: ensure the MongoDB service is stopped
    service: name=mongod state=stopped enabled=no

  - name: removing packages
    apt: name={{ item }} update_cache=true purge=yes state=absent
    with_items:
    - mongodb-org
    - mongodb-org-mongos
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools
    when: ansible_distribution == "Ubuntu"

  - name: removing datafiles
    file: path={{ item }} state=absent
    with_items:
    - /var/lib/mongodb/
    - /var/lib/mongodb/
    - /etc/mongodb/

